### ISSUE TITLE
Images not available for IB_DESIGNABLE views

### ISSUE THREAD

**Issue by brockboland** [vokal/Cat2Cat#12]
On a UIView subclass, I have a `commonSetup` method that's called both from `awakeFromNib` and `prepareForInterfaceBuilder`. The `commonSetup` populates a UIImageView using a Cat2Cat method, so that the image will be visible both in the app and in IB. It works in-app, but but in IB.

The problem is that IB_DESIGNABLE views are handled by an Xcode helper instead of the actual app. Info here: http://stackoverflow.com/a/24604071/2185

One possible solution is to use `imageNamed:inBundle:compatibleWithTraitCollection:` instead of `imageNamed:`, but this is kind of clunky: it would require importing some custom class from the app (like the app delegate or something) to get the bundle for that class, like so:

```objc
+ (UIImage *)ac_Facebook
{
    NSBundle *imageBundle = [NSBundle bundleForClass:[MyAppDelegate class]];
    return [UIImage imageNamed:@"Facebook"
                      inBundle:imageBundle
 compatibleWithTraitCollection:nil];
}
```

Any thoughts, concerns, or other ideas to work around this?

**Comment by designatednerd** [comment]
Workaround available in #19.
