### ISSUE TITLE
Missing Binary in latest release

### ISSUE THREAD

**Issue by netbe** [vokal/Cat2Cat#27]
Hi,

I noticed the Pre-Compiled Binary is not included in latest releases, is this way not supported anymore?

Cheers

**Comment by vokal-isaac** [comment]
I think that was an unintentional oversight.  The pre-compiled binary is also at https://github.com/vokal/Cat2Cat/blob/master/CocoaPod/Cat2Cat (click "View Raw" to download it).

**Comment by designatednerd** [comment]
Yep, totally my bad! It is now added on the release as well. Thank you for letting us know!
