### ISSUE TITLE
Update Swift for 2.0

### ISSUE THREAD

**Issue by designatednerd** [vokal/Cat2Cat#29]
We should look at some of the fun stuff like using protocols and enums to make sure the images aren't optional.

**Comment by vokal-isaac** [comment]
Whether the images are option is really more a function of how `UIImage`'s methods are declared.  My inclination would be to keep the Cat2Cat methods behaving as similarly to the built-in stringly-typed methods as possible, but :shrug:.

**Comment by designatednerd** [comment]
Right, but there's a fun way you can do this in Swift 2.0 that makes it really easy to set up an extension that takes an enum. I'll see if I can get it up and running. :smile:
